### ISSUE TITLE
C-Stick inversion is undone if game left paused

### ISSUE THREAD

**Issue by MDHEXT** [JoshuaMKW/BetterSunshineEngine#12] opened 2023-09-09 20:26 UTC
The option to invert the camera controls is reverted if you pause the game for an extended period of time. When the game is resumed, the camera controls revert to their original state.

**Comment by JoshuaMKW** [comment] 2024-02-01 16:31
After testing, I was unable to reproduce this error. I'm closing this issue until further notice, feel free to revisit this with further details on your environment (which modules you have active) and what version they are.

**Closed as completed by JoshuaMKW** 2024-02-01 16:31 UTC
Labels: bug
